
[theme]
primaryColor = "#4CAF50"
backgroundColor = "#1A1C1E"
secondaryBackgroundColor = "#232527"
textColor = "#FFFFFF"
font = "Montserrat"

[server]
enableCORS = false
enableXsrfProtection = false


[client]
toolbarMode = "minimal"

