
[theme]
primaryColor = "#4285F4"
backgroundColor = "#1E2326"
secondaryBackgroundColor = "#2A2E32"
textColor = "#FFFFFF"
font = "Encode Sans Condensed"

[server]
headless = true
enableCORS = false
address = "0.0.0.0"
port = 5000

[client]
toolbarMode = "minimal"
