
[theme]
primaryColor = "#4CAF50"
backgroundColor = "#1A1C1E"
secondaryBackgroundColor = "#232527"
textColor = "#FFFFFF"
font = "Montserrat"

[server]
headless = true
enableCORS = false
address = "0.0.0.0"
port = 5000

[client]
toolbarMode = "minimal"
