
[theme]
primaryColor = "#4285F4"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[server]
headless = true
enableCORS = false
address = "0.0.0.0"
port = 5000

[theme]
font = "Encode Sans Condensed"

[client]
toolbarMode = "minimal"
